NCDC15_WWW_django/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.http import HttpResponseRedirect

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('cgi_bin.urls', namespace="cgi-bin")),
)

cgi_bin/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required
from cgi_bin import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^bottom/$', views.bottom, name='bottom'),
    url(r'^bottom2/$', views.bottom2, name='bottom2'),
    url(r'^branches/$', views.branches, name='branches'),
    url(r'^cgi-bin/actions/get-admin-access-token$', views.admintoken, name='admintoken'),
    url(r'^cgi-bin/show/landing/$', login_required(views.landing), name='landing'),
    url(r'^cgi-bin/show/show-user$', views.show_user, name='show_user'),
    url(r'^cgi-bin/actions/find-user$', views.find_user, name='find_user'),
    url(r'^cgi-bin/actions/create-user$', views.create_user, name='create_user'),
    url(r'^cgi-bin/actions/delete-user$', views.delete_user, name='delete_user'),
    url(r'^cgi-bin/actions/make-deposit$', views.make_deposit, name='make_deposit'),
    url(r'^cgi-bin/actions/make-withdrawal$', views.make_withdrawal, name='make_withdrawal'),
    url(r'^cgi-bin/actions/make-payment$', views.make_payment, name='make_payment'),
    url(r'^cgi-bin/login/$', 'django.contrib.auth.views.login', {'template_name': 'cgi_bin/not-logged-in.html'}, name='login'),
    url(r'^cgi-bin/logout/$', 'django.contrib.auth.views.logout', {'next_page': 'cgi-bin:login'}, name='logout'),
)

cgi_bin/models.py
from django.db import models
from django.contrib.auth.models import User

class BankUser(models.Model):
    def __str__(self):
        return self.user.username
    user = models.OneToOneField(User, )
    balance = models.IntegerField(default=0)

class Transaction(models.Model):
    def __str__(self):
        return self.typeof
    user = models.ForeignKey(BankUser)
    typeof = models.CharField(default='', max_length=100)
    balance = models.IntegerField(default=0)
    credit = models.IntegerField(default=0)
    debit = models.IntegerField(default=0)

class AdminSession(models.Model):
    def __str__(self):
        return self.access_token
    access_token = models.CharField(default='', max_length=50)
    date = models.TimeField(auto_now=True)

cgi_bin/views.py
from django.shortcuts import render, get_object_or_404
from cgi_bin.models import BankUser, Transaction, AdminSession
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User
from django.core.files import File
from django.contrib.auth import authenticate
from datetime import datetime


def index(request):
    return render(request, 'cgi_bin/index.html')

def bottom(request):
    return render(request, 'cgi_bin/bottom.html')

def bottom2(request):
    return render(request, 'cgi_bin/bottom2.html')

def branches(request):
    return render(request, 'cgi_bin/branches.html')

def landing(request):
    return render(request, 'cgi_bin/welcome.html')

def make_payment(request):
    if request.user.is_authenticated():
        user = request.user.bankuser
        redir = '../show/show-user'
    elif has_admin_token(request) and User.objects.filter(username=request.GET['user_name']).exists():
        user = BankUser.objects.get(user=User.objects.get(username=request.GET['user_name']))
        redir = '../show/show-user?user_name=' + user.user.username
    else:
        return HttpResponseRedirect('../login')
    if request.REQUEST['other_party'] and request.REQUEST['amount']:
        dest_user = get_object_or_404(User, username=request.REQUEST['other_party'])
        amount = int(request.REQUEST['amount'])
        if amount > 0:
            if dest_user:
                if user.balance - amount >= 0:
                    user.balance -= amount
                    user.save()
                    t1 = Transaction(user=user, debit=amount, typeof=dest_user, balance=user.balance)
                    t1.save()
                    dest_user.bankuser.balance += amount
                    dest_user.bankuser.save()
                    t2 = Transaction(user=dest_user.bankuser, credit=amount, typeof=user, balance=dest_user.bankuser.balance)
                    t2.save()
                    return HttpResponseRedirect(redir)
                else:
                    return HttpResponse("You do not have enough money to complete this transfer.")
            else:
                return HttpResponse("The target user was not found.")
        else:
            return HttpResponse("You cannot request this kind of transfer.")

def show_user(request):
    if has_admin_token(request):
      result = BankUser.objects.get(user=User.objects.get(username=request.GET['user_name']))
    elif request.user.is_authenticated():
      result = request.user.bankuser
    else:
      return HttpResponseRedirect('../login')
    transaction_history = Transaction.objects.filter(user=result).order_by('pk')
    context = {'transaction_history': transaction_history, 'user' : result}
    return render(request, 'cgi_bin/show-user.html', context)

def admintoken(request):
    if request.meta['REMOTE_ADDR'] == '192.168.1.4':
        attempt = request.GET['password']
        f = open( '/usr/lib/db/pass_Administrator', 'r' )
        passwd = f.readline().rstrip()
        f.close()
        if passwd == attempt:
            try:
                token = hex(AdminSession.objects.all().reverse()[0].pk + 314758926 * int((datetime.now()-datetime(1970,1,1)).total_seconds()))[2:]
            except IndexError:
                token = hex(314758926 * int((datetime.now()-datetime(1970,1,1)).total_seconds()))[2:]
            session = AdminSession(access_token=token)
            session.save()
            response = HttpResponse('access_token=')
            response.set_cookie('access_token', token)
            return response
        else:
            return HttpResponse("Wrong!")

def has_admin_token(request):
  return AdminSession.objects.filter(access_token=request.COOKIES.get('access_token', False)).exists() and request.meta['REMOTE_ADDR'] == '192.168.1.4'

def find_user(request):
   if has_admin_token(request):
       user = User.objects.get(username=request.GET['user_name'])
       if user:
           return HttpResponse(user.bankuser.balance)
       else:
           return HttpResponse("User not found!")

def create_user(request):
   if has_admin_token(request):
       newuser = User(username=request.GET['name'])
       newuser.set_password(request.GET['password'])
       newuser.save()
       newbankuser = BankUser(user=newuser)
       newbankuser.save()
       initial = Transaction(user=newbankuser, typeof='Initial')
       initial.save()
       return HttpResponseRedirect("../show/show-user?user_name=" + newuser.username)

def delete_user(request):
   if has_admin_token(request):
       deluser = User.objects.get(username=request.GET['user_name'])
       if deluser:
           delbankuser = BankUser.objects.get(user=deluser)
           delbankuser.delete()
           deluser.delete()
           return HttpResponse("User " + request.GET['user_name'] + " deleted!")
       else:
           return HttpResponse("User " + request.GET['user_name'] + " not found!")

def make_deposit(request):
    if has_admin_token(request) and request.GET['user_name'] and request.GET['amount']:
        user = get_object_or_404(User, username=request.REQUEST['user_name'])
        amount = int(request.GET['amount'])
        if amount > 0:
            user.bankuser.balance += amount
            user.bankuser.save()
            transaction = Transaction(user=user.bankuser, typeof="Deposit", balance=user.bankuser.balance, credit=amount)
            transaction.save()
            return HttpResponseRedirect("../show/show-user?user_name=" + user.username)

def make_withdrawal(request):
    if has_admin_token(request) and request.GET['user_name'] and request.GET['amount']:
        user = get_object_or_404(User, username=request.REQUEST['user_name'])
        amount = int(request.GET['amount'])
        if amount > 0 and user.bankuser.balance - amount >= 0:
            user.bankuser.balance -= amount
            user.bankuser.save()
            transaction = Transaction(user=user.bankuser, typeof="Withdrawal", balance=user.bankuser.balance, debit=amount)
            transaction.save()
            return HttpResponseRedirect("../show/show-user?user_name=" + user.username)

cgi_bin/templates/cgi_bin/50x.html
<!DOCTYPE html>
<html>
<head>
<title>Error</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>An error occurred.</h1>
<p>Sorry, the page you are looking for is currently unavailable.<br/>
Please try again later.</p>
<p>If you are the system administrator of this resource then you should check
the <a href="http://nginx.org/r/error_log">error log</a> for details.</p>
<p><em>Faithfully yours, nginx.</em></p>
</body>
</html>

cgi_bin/templates/cgi_bin/bottom.html
{% load staticfiles %}
<html>
  <body bgcolor=grey>
    <center>
      <p/>
        <img height=100 src="{% static 'cgi_bin/images/ssl_badge.gif' %}">
        <img height=100 src="{% static 'cgi_bin/images/badge3.jpg' %}">
        <img height=100 src="{% static 'cgi_bin/images/ssl-badge.png' %}">
        <img height=100 src="{% static 'cgi_bin/images/badge2.gif' %}">
        <img height=100 src="{% static 'cgi_bin/images/badge7.png' %}">
        <img height=100 src="{% static 'cgi_bin/images/badge.png' %}">
        <img height=100 src="{% static 'cgi_bin/images/ssl.png' %}">
        </p>

      </center>
    </body>
  </html>

cgi_bin/templates/cgi_bin/bottom2.html
{% load staticfiles %}
<html>
  <body bgcolor=grey>
    <center>
      <p/>
        <img height=100 src="{% static 'cgi_bin/images/pci.jpg' %}">
        <img height=100 src="{% static 'cgi_bin/images/badge4.jpg' %}">
        <img height=100 src="{% static 'cgi_bin/images/badge5.jpg' %}">
        <img height=100 src="{% static 'cgi_bin/images/ssl_badge.gif' %}">
        <img height=100 src="{% static 'cgi_bin/images/badge3.jpg' %}">
        <img height=100 src="{% static 'cgi_bin/images/ssl-badge.png' %}">
        <img height=100 src="{% static 'cgi_bin/images/badge2.gif' %}">
        <img height=100 src="{% static 'cgi_bin/images/badge7.png' %}">
        </p>

      </center>
    </body>
  </html>

cgi_bin/templates/cgi_bin/branches.html
<html>
  <head>
    <title>CDC Investment Bank and Trust</title>
    </head>
    <script>
    function doBlink() {
      // Blink, Blink, Blink...
      var blink =  document.getElementsByTagName("blink");
        for (var i=0; i < blink.length; i++)
          blink[i].style.visibility = blink[i].style.visibility == "" ? "hidden" : ""
    }

    function startBlink() {

    setInterval("doBlink()",1000);
    }
    window.onload = startBlink;
    </script>

  <body bgcolor=grey>
    <center>
      <h2>Washington, DC Branch</h2>
      <p>
        Tel: 1-866-672-4473 <br/>
        Addr: 1600 Pennsylvania
        Avenue Northwest, Washington, DC 20500
        </p>
      {% load staticfiles %}
        <h2><img src={% static 'cgi_bin/images/new2.gif' %}> Ames, IA Branch</h2>
      <p>
        Tel: 1-555-733-8326 <br/>
        Addr: 1212 Coover Hall, Ames, IA 50010
        </p>

      </center>

    <iframe width=100% scrolling=no frameborder=none src="{% url 'cgi-bin:bottom' %}"/>

    </body>
  </html>

cgi_bin/templates/cgi_bin/create-user.html
<html>
  <body>
    <form action="/cgi-bin/actions/create-user" method="POST">
      Name:<input type="text" name="name"><br>
      Password:<input type="password" name="password"><br>
      Repeat password:<input type="password" name="unused_field">
      <input type="submit" text="Submit!">
      </form>

    </body>

  </html>

cgi_bin/templates/cgi_bin/delete-user.html
<html>
<body>
<form action="/cgi-bin/actions/delete-user" method="POST">
Name:<input type="text" name="user_name">
<input type="submit" text="Submit!">
</form>
</body>
</html>

cgi_bin/templates/cgi_bin/index.html
{% load staticfiles %}
<html>
  <head>
    <title>CDC Investment Bank and Trust</title>
    </head>
    <script>
    function doBlink() {
      // Blink, Blink, Blink...
      var blink =  document.getElementsByTagName("blink");
        for (var i=0; i < blink.length; i++)
          blink[i].style.visibility = blink[i].style.visibility == "" ? "hidden" : ""
    }

    function startBlink() {

    setInterval("doBlink()",1000);
    }
    window.onload = startBlink;
    </script>

  <body bgcolor=grey>
    <center>
      <h1>Welcome to CDC Investment Bank and Trust, LTD</h1>
      <hr/>
      <img height=100 src="{% static 'cgi_bin/images/badge4.jpg' %}">
      <img height=100 src="{% static 'cgi_bin/images/badge5.jpg' %}">
      <img height=100 src="{% static 'cgi_bin/images/badge6.jpg' %}">
      <hr/>
      <h1>
          <a href="{% url 'cgi-bin:landing' %}">
            <blink>Click here to enter our secure site </blink>
          </a>
          </h1>

      <hr/>
      <p><img src="{% static 'cgi_bin/images/pci.jpg' %}"></p>
      <hr/>
      </center>

    <iframe width=100% scrolling=no frameborder=none src="{% url 'cgi-bin:bottom' %}"/>

    </body>
  </html>

cgi_bin/templates/cgi_bin/not-logged-in.html
<html>
  <head>
    <title>CDC Investment Bank and Trust</title>
    </head>
    <script>
    function doBlink() {
      // Blink, Blink, Blink...
      var blink =  document.getElementsByTagName("blink");
        for (var i=0; i < blink.length; i++)
          blink[i].style.visibility = blink[i].style.visibility == "" ? "hidden" : ""
    }

    function startBlink() {

    setInterval("doBlink()",1000);
    }
    window.onload = startBlink;
    </script>

  <body bgcolor=grey>
    <center>
      <h2>Log in with the form below</h2>
      <form action="{% url 'cgi-bin:login' %}" method="post">
        {% csrf_token %}
        Name{{ form.username }}<br/>
        Password{{ form.password }}
        <input type="submit" value="login"/>
        <input type="hidden" name="next" value="{{ next }}" />
        </form>
        {% if form.errors %}
        <p style="color:yellow">Your username and password didn't match. Please try again.</p>
        {% endif %}
      <hr/>
      <h4>
        Don't have an account? Visit one of our
        <a href="{% url 'cgi-bin:branches' %}">branches!</a>
        </h4>

      </center>

    <hr/>
    <iframe width=100% scrolling=no frameborder=none src="{% url 'cgi-bin:bottom2' %}"/>
    </body>
  </html>

cgi_bin/templates/cgi_bin/show-user.html
<html>
<style type="text/css">table, td, th { border: 1px solid black;}</style>

<body bgcolor=grey>
<center>
<h1>{{ user }}'s Account</h1>
    <h3>Balance: {{ user.balance }}</h3>
<h2>Transaction History</h2>
<table>
    <tr>
        <th>Transaction</th>
        <th>Debit</th>
        <th>Credit</th>
        <th>Balance</th>
    </tr>
    {% for t in transaction_history %}
    <tr>
        <td>{{ t.typeof }}</td>
        <td{% if t.debit > 0 %} bgcolor=salmon>{{ t.debit }}{% else %}>---{% endif %}</td>
        <td{% if t.credit > 0 %} bgcolor=limegreen>{{ t.credit }}{% else %}>---{% endif %}</td>
        <td bgcolor=lightsteelblue>{{ t.balance }}</td>
    {% endfor %}
</table>
<a href="{% url 'cgi-bin:landing' %}">Back</a>
</center><hr/>
<iframe src="{% url 'cgi-bin:bottom2' %}" scrolling=no frameborder=none width=100%>
</body></html>

cgi_bin/templates/cgi_bin/welcome.html
<html>
  <head>
    <title>CDC Investment Bank and Trust</title>
    </head>
    <script>
    function doBlink() {
      // Blink, Blink, Blink...
      var blink =  document.getElementsByTagName("blink");
        for (var i=0; i < blink.length; i++)
          blink[i].style.visibility = blink[i].style.visibility == "" ? "hidden" : ""
    }

    function startBlink() {

    setInterval("doBlink()",1000);
    }
    window.onload = startBlink;
    </script>

  <body bgcolor=grey>
    <center>
      <h1>
        Welcome {{ user }}! Use the links below to navigate.
        </h1>

      <a href="{% url 'cgi-bin:show_user' %}">
        <h3>View Account</h3>
        </a>

      <h3>
        {% load staticfiles %}
        <img src="{% static 'cgi_bin/images/new.gif' %}">
        Automatic Online Transfers
        <img src="{% static 'cgi_bin/images/new.gif' %}">
        </h3>

      <p>Enter recipient name and amount below to submit a transfer</p>
      <p>
        <form action="{% url 'cgi-bin:make_payment' %}" method="post">
          {% csrf_token %}
          Recipient: <input type=text name=other_party>
          Amount: $<input type=text name=amount size=4>
          <input type=submit>
          </form>
        </p>

      <a href="{% url 'cgi-bin:logout' %}">Log out</a>
      <p>
        Contact our Washington, DC <a href="{% url 'cgi-bin:branches' %}">branch</a>
        for web support. Tel: 1-866-672-4473
        </p>
      </center>

    <hr/>
    <iframe width=100% scrolling=no frameborder=none src="{% url 'cgi-bin:bottom' %}"/>
    </body>
  </html>